---
global:
  width: 400
  height: 200
  bits: 32
  plugin:
    path: cmake-build-debug/plugins

pipes:
  filling:
    __order: 1
    color:
      random:
        min: 10
        max: 100
      r: -1
      g: -1
      b: -1
    test: aaaa
  background:
    __order: 2
    image_dir: resource/background
  noise:
    __order: 3
    color:
      random:
        min: 10
        max: 150
      r: -1
      g: -1
      b: -1
    type: "line"
    param:
      line_number: 50
  deformation:
    __order: 4
    none: 0