---
global:
  width: 256
  height: 200
  bits: 32
  plugin:
    path: cmake-build-debug/plugins

pipes:
  filling:
    color:
      random:
        min: 10
        max: 200
      r: -1
      g: -1
      b: -1
    test: aaaa
  noise:
    color:
      random:
        min: 10
        max: 200
      r: -1
      g: -1
      b: -1
    type: "line"