---
global:
  width: 200
  height: 100
  bits: 32
  plugin:
    path: cmake-build-debug/plugins

pipes:
  filling:
    color:
      random:
        min: 10
        max: 100
      r: -1
      g: -1
      b: -1
    test: aaaa
  noise:
    color:
      random:
        min: 10
        max: 150
      r: -1
      g: -1
      b: -1
    type: "line"
    param:
      line_number: 200